# Generated by Django 3.1 on 2020-08-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("author", models.CharField(max_length=100)),
                ("published", models.BooleanField(default=False)),
                ("uses", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "problem",
                "verbose_name_plural": "problems",
            },
        ),
    ]
