# Generated by Django 3.1 on 2020-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_auto_20200928_1441"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="author",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
